# AWS Permission Scoring Configuration
# This file defines how AWS actions are scored for risk assessment

# Risk levels and their numeric scores
risk_levels:
  minimal: 1
  low: 3
  medium: 5
  high: 8
  critical: 10

# Default scores for unknown actions
defaults:
  read_score: 2
  write_score: 5
  admin_score: 0

# Global scoring rules
scoring_rules:
  # Weights for combining different scoring methods
  weights:
    managed_policy: 0.4
    inline_policy: 0.6

# Service-specific action categorization
services:
  # AWS Identity and Access Management (IAM) - High risk for privilege escalation
  iam:
    actions:
      # Critical IAM actions that can lead to privilege escalation
      "iam:AttachUserPolicy":
        risk_level: critical
        description: "Can escalate privileges by attaching policies to users"
      "iam:AttachRolePolicy":
        risk_level: critical
        description: "Can escalate privileges by attaching policies to roles"
      "iam:AttachGroupPolicy":
        risk_level: critical
        description: "Can escalate privileges by attaching policies to groups"
      "iam:CreateRole":
        risk_level: critical
        description: "Can create new roles for privilege escalation"
      "iam:CreateUser":
        risk_level: critical
        description: "Can create new users with elevated privileges"
      "iam:CreatePolicy":
        risk_level: critical
        description: "Can create policies with elevated permissions"
      "iam:PutUserPolicy":
        risk_level: critical
        description: "Can add inline policies to users"
      "iam:PutRolePolicy":
        risk_level: critical
        description: "Can add inline policies to roles"
      "iam:PutGroupPolicy":
        risk_level: critical
        description: "Can add inline policies to groups"
      "iam:UpdateAssumeRolePolicy":
        risk_level: critical
        description: "Can modify role trust relationships"
      "iam:PassRole":
        risk_level: critical
        description: "Can pass roles to AWS services for privilege escalation"
      "iam:CreateAccessKey":
        risk_level: critical
        description: "Can create programmatic access keys"
      "iam:UpdateAccessKey":
        risk_level: high
        description: "Can modify access key status"
      "iam:CreateLoginProfile":
        risk_level: critical
        description: "Can create console access for users"
      "iam:UpdateLoginProfile":
        risk_level: high
        description: "Can modify user console access"
      "iam:ChangePassword":
        risk_level: medium
        description: "Can change user passwords"
      "iam:CreateServiceLinkedRole":
        risk_level: high
        description: "Can create service-linked roles"

      # High risk IAM actions
      "iam:DeleteRole":
        risk_level: high
        description: "Can delete IAM roles"
      "iam:DeleteUser":
        risk_level: high
        description: "Can delete IAM users"
      "iam:DeletePolicy":
        risk_level: high
        description: "Can delete IAM policies"
      "iam:DetachUserPolicy":
        risk_level: high
        description: "Can remove policies from users"
      "iam:DetachRolePolicy":
        risk_level: high
        description: "Can remove policies from roles"
      "iam:DetachGroupPolicy":
        risk_level: high
        description: "Can remove policies from groups"
      "iam:DeleteUserPolicy":
        risk_level: high
        description: "Can delete inline user policies"
      "iam:DeleteRolePolicy":
        risk_level: high
        description: "Can delete inline role policies"
      "iam:DeleteGroupPolicy":
        risk_level: high
        description: "Can delete inline group policies"
      "iam:DeleteAccessKey":
        risk_level: medium
        description: "Can delete access keys"
      "iam:DeleteLoginProfile":
        risk_level: medium
        description: "Can delete user console access"

      # Medium risk IAM actions
      "iam:TagRole":
        risk_level: medium
        description: "Can tag IAM roles"
      "iam:TagUser":
        risk_level: medium
        description: "Can tag IAM users"
      "iam:TagPolicy":
        risk_level: medium
        description: "Can tag IAM policies"
      "iam:UntagRole":
        risk_level: medium
        description: "Can remove tags from IAM roles"
      "iam:UntagUser":
        risk_level: medium
        description: "Can remove tags from IAM users"
      "iam:UntagPolicy":
        risk_level: medium
        description: "Can remove tags from IAM policies"

    # Low risk IAM actions (read-only)
    read_only_actions:
      - "iam:GetRole"
      - "iam:GetUser"
      - "iam:GetPolicy"
      - "iam:ListRoles"
      - "iam:ListUsers"
      - "iam:ListPolicies"
      - "iam:ListAttachedRolePolicies"
      - "iam:ListAttachedUserPolicies"
      - "iam:ListRolePolicies"
      - "iam:ListUserPolicies"
      - "iam:GetRolePolicy"
      - "iam:GetUserPolicy"
      - "iam:SimulatePrincipalPolicy"
      - "iam:SimulateCustomPolicy"

  # AWS Key Management Service (KMS) - Encryption context matters
  kms:
    # Read-only actions (including decrypt for accessing encrypted resources)
    read_only_actions:
      - "kms:Decrypt"           # Should be read-only as it's needed to access encrypted data
      - "kms:DescribeKey"
      - "kms:GetKeyPolicy"
      - "kms:GetKeyRotationStatus"
      - "kms:ListKeys"
      - "kms:ListAliases"
      - "kms:ListGrants"
      - "kms:ListKeyPolicies"
      - "kms:ListResourceTags"

    # Medium risk actions
    medium_risk_actions:
      - "kms:Encrypt"
      - "kms:GenerateDataKey"
      - "kms:GenerateDataKeyWithoutPlaintext"
      - "kms:ReEncrypt"
      - "kms:CreateGrant"
      - "kms:RetireGrant"
      - "kms:RevokeGrant"

    # High risk actions
    high_risk_actions:
      - "kms:CreateKey"
      - "kms:CreateAlias"
      - "kms:DeleteAlias"
      - "kms:UpdateAlias"
      - "kms:PutKeyPolicy"
      - "kms:EnableKey"
      - "kms:DisableKey"
      - "kms:EnableKeyRotation"
      - "kms:DisableKeyRotation"
      - "kms:TagResource"
      - "kms:UntagResource"

    # Critical actions
    critical_actions:
      - "kms:ScheduleKeyDeletion"
      - "kms:CancelKeyDeletion"

  # Amazon S3 - Data access and management
  s3:
    read_only_actions:
      - "s3:GetObject"
      - "s3:GetObjectVersion"
      - "s3:GetBucketLocation"
      - "s3:GetBucketVersioning"
      - "s3:GetBucketPolicy"
      - "s3:GetBucketAcl"
      - "s3:ListBucket"
      - "s3:ListAllMyBuckets"
      - "s3:GetObjectAcl"
      - "s3:GetObjectVersionAcl"

    medium_risk_actions:
      - "s3:PutObject"
      - "s3:PutObjectAcl"
      - "s3:PutObjectVersionAcl"
      - "s3:DeleteObject"
      - "s3:DeleteObjectVersion"
      - "s3:RestoreObject"

    high_risk_actions:
      - "s3:CreateBucket"
      - "s3:DeleteBucket"
      - "s3:PutBucketPolicy"
      - "s3:DeleteBucketPolicy"
      - "s3:PutBucketAcl"
      - "s3:PutBucketVersioning"
      - "s3:PutBucketEncryption"
      - "s3:DeleteBucketEncryption"

    critical_actions:
      - "s3:PutBucketPublicAccessBlock"
      - "s3:DeleteBucketPublicAccessBlock"

  # Amazon EC2 - Compute resources
  ec2:
    read_only_actions:
      - "ec2:DescribeInstances"
      - "ec2:DescribeImages"
      - "ec2:DescribeSecurityGroups"
      - "ec2:DescribeVpcs"
      - "ec2:DescribeSubnets"
      - "ec2:DescribeVolumes"
      - "ec2:DescribeSnapshots"
      - "ec2:DescribeKeyPairs"
      - "ec2:DescribeNetworkAcls"
      - "ec2:DescribeRouteTables"
      - "ec2:DescribeInternetGateways"
      - "ec2:DescribeNatGateways"

    medium_risk_actions:
      - "ec2:RunInstances"
      - "ec2:StartInstances"
      - "ec2:StopInstances"
      - "ec2:RebootInstances"
      - "ec2:CreateTags"
      - "ec2:DeleteTags"
      - "ec2:CreateVolume"
      - "ec2:AttachVolume"
      - "ec2:DetachVolume"

    high_risk_actions:
      - "ec2:TerminateInstances"
      - "ec2:CreateSecurityGroup"
      - "ec2:DeleteSecurityGroup"
      - "ec2:AuthorizeSecurityGroupIngress"
      - "ec2:AuthorizeSecurityGroupEgress"
      - "ec2:RevokeSecurityGroupIngress"
      - "ec2:RevokeSecurityGroupEgress"
      - "ec2:DeleteVolume"
      - "ec2:CreateKeyPair"
      - "ec2:DeleteKeyPair"
      - "ec2:ImportKeyPair"

    critical_actions:
      - "ec2:ModifyInstanceAttribute"
      - "ec2:CreateImage"
      - "ec2:DeregisterImage"
      - "ec2:ModifyImageAttribute"
      - "ec2:ResetImageAttribute"

  # Amazon VPC - Network infrastructure (CRITICAL for security)
  vpc:
    read_only_actions:
      - "ec2:DescribeVpcs"
      - "ec2:DescribeSubnets"
      - "ec2:DescribeRouteTables"
      - "ec2:DescribeInternetGateways"
      - "ec2:DescribeNatGateways"
      - "ec2:DescribeVpcEndpoints"
      - "ec2:DescribeNetworkAcls"
      - "ec2:DescribeVpcPeeringConnections"
      - "ec2:DescribeCustomerGateways"
      - "ec2:DescribeVpnGateways"
      - "ec2:DescribeVpnConnections"
      - "ec2:DescribeTransitGateways"
      - "ec2:DescribeFlowLogs"

    medium_risk_actions:
      - "ec2:CreateVpcEndpoint"
      - "ec2:DeleteVpcEndpoint"
      - "ec2:ModifyVpcEndpoint"
      - "ec2:CreateFlowLogs"
      - "ec2:DeleteFlowLogs"
      - "ec2:CreateTags"
      - "ec2:DeleteTags"

    high_risk_actions:
      - "ec2:CreateVpc"
      - "ec2:DeleteVpc"
      - "ec2:ModifyVpcAttribute"
      - "ec2:CreateSubnet"
      - "ec2:DeleteSubnet"
      - "ec2:ModifySubnetAttribute"
      - "ec2:CreateRouteTable"
      - "ec2:DeleteRouteTable"
      - "ec2:CreateRoute"
      - "ec2:DeleteRoute"
      - "ec2:ReplaceRoute"
      - "ec2:AssociateRouteTable"
      - "ec2:DisassociateRouteTable"
      - "ec2:CreateNetworkAcl"
      - "ec2:DeleteNetworkAcl"
      - "ec2:CreateNetworkAclEntry"
      - "ec2:DeleteNetworkAclEntry"
      - "ec2:ReplaceNetworkAclEntry"
      - "ec2:ReplaceNetworkAclAssociation"

    critical_actions:
      - "ec2:CreateInternetGateway"
      - "ec2:DeleteInternetGateway"
      - "ec2:AttachInternetGateway"
      - "ec2:DetachInternetGateway"
      - "ec2:CreateNatGateway"
      - "ec2:DeleteNatGateway"
      - "ec2:CreateVpcPeeringConnection"
      - "ec2:DeleteVpcPeeringConnection"
      - "ec2:AcceptVpcPeeringConnection"
      - "ec2:RejectVpcPeeringConnection"
      - "ec2:CreateVpnConnection"
      - "ec2:DeleteVpnConnection"
      - "ec2:CreateCustomerGateway"
      - "ec2:DeleteCustomerGateway"
      - "ec2:CreateVpnGateway"
      - "ec2:DeleteVpnGateway"
      - "ec2:AttachVpnGateway"
      - "ec2:DetachVpnGateway"

  # AWS Security Groups - Network security rules (CRITICAL)
  security_groups:
    read_only_actions:
      - "ec2:DescribeSecurityGroups"
      - "ec2:DescribeSecurityGroupRules"

    critical_actions:
      - "ec2:CreateSecurityGroup"
      - "ec2:DeleteSecurityGroup"
      - "ec2:AuthorizeSecurityGroupIngress"
      - "ec2:AuthorizeSecurityGroupEgress"
      - "ec2:RevokeSecurityGroupIngress"
      - "ec2:RevokeSecurityGroupEgress"
      - "ec2:ModifySecurityGroupRules"

  # AWS WAF - Web Application Firewall (CRITICAL for security)
  waf:
    read_only_actions:
      - "waf:GetWebACL"
      - "waf:ListWebACLs"
      - "waf:GetRule"
      - "waf:ListRules"
      - "waf:GetIPSet"
      - "waf:ListIPSets"
      - "waf:GetByteMatchSet"
      - "waf:ListByteMatchSets"
      - "waf:GetSqlInjectionMatchSet"
      - "waf:ListSqlInjectionMatchSets"

    high_risk_actions:
      - "waf:CreateWebACL"
      - "waf:UpdateWebACL"
      - "waf:CreateRule"
      - "waf:UpdateRule"
      - "waf:CreateIPSet"
      - "waf:UpdateIPSet"
      - "waf:CreateByteMatchSet"
      - "waf:UpdateByteMatchSet"

    critical_actions:
      - "waf:DeleteWebACL"
      - "waf:DeleteRule"
      - "waf:DeleteIPSet"
      - "waf:DeleteByteMatchSet"

  # AWS Shield - DDoS Protection (CRITICAL)
  shield:
    read_only_actions:
      - "shield:DescribeProtection"
      - "shield:ListProtections"
      - "shield:DescribeSubscription"
      - "shield:GetSubscriptionState"

    high_risk_actions:
      - "shield:CreateProtection"
      - "shield:CreateSubscription"

    critical_actions:
      - "shield:DeleteProtection"
      - "shield:DeleteSubscription"

  # AWS GuardDuty - Threat Detection (CRITICAL)
  guardduty:
    read_only_actions:
      - "guardduty:GetDetector"
      - "guardduty:ListDetectors"
      - "guardduty:GetFindings"
      - "guardduty:ListFindings"
      - "guardduty:GetIPSet"
      - "guardduty:ListIPSets"
      - "guardduty:GetThreatIntelSet"
      - "guardduty:ListThreatIntelSets"

    medium_risk_actions:
      - "guardduty:CreateIPSet"
      - "guardduty:UpdateIPSet"
      - "guardduty:CreateThreatIntelSet"
      - "guardduty:UpdateThreatIntelSet"
      - "guardduty:ArchiveFindings"
      - "guardduty:UnarchiveFindings"

    high_risk_actions:
      - "guardduty:CreateDetector"
      - "guardduty:UpdateDetector"

    critical_actions:
      - "guardduty:DeleteDetector"
      - "guardduty:DeleteIPSet"
      - "guardduty:DeleteThreatIntelSet"

  # AWS Config - Configuration compliance (HIGH security impact)
  config:
    read_only_actions:
      - "config:GetComplianceDetailsByConfigRule"
      - "config:GetComplianceDetailsByResource"
      - "config:GetComplianceSummaryByConfigRule"
      - "config:GetComplianceSummaryByResourceType"
      - "config:GetConfigurationHistory"
      - "config:GetResourceConfigHistory"
      - "config:ListConfigurationRecorders"
      - "config:ListDeliveryChannels"
      - "config:DescribeConfigRules"
      - "config:DescribeConfigurationRecorders"
      - "config:DescribeDeliveryChannels"

    medium_risk_actions:
      - "config:PutConfigRule"
      - "config:PutEvaluations"
      - "config:StartConfigRulesEvaluation"

    high_risk_actions:
      - "config:PutConfigurationRecorder"
      - "config:PutDeliveryChannel"
      - "config:StartConfigurationRecorder"

    critical_actions:
      - "config:DeleteConfigRule"
      - "config:DeleteConfigurationRecorder"
      - "config:DeleteDeliveryChannel"
      - "config:StopConfigurationRecorder"

  # AWS CloudTrail - Audit logging (CRITICAL for compliance)
  cloudtrail:
    read_only_actions:
      - "cloudtrail:DescribeTrails"
      - "cloudtrail:GetTrailStatus"
      - "cloudtrail:LookupEvents"
      - "cloudtrail:GetEventSelectors"
      - "cloudtrail:GetInsightSelectors"

    medium_risk_actions:
      - "cloudtrail:PutEventSelectors"
      - "cloudtrail:PutInsightSelectors"
      - "cloudtrail:AddTags"
      - "cloudtrail:RemoveTags"

    high_risk_actions:
      - "cloudtrail:CreateTrail"
      - "cloudtrail:UpdateTrail"
      - "cloudtrail:StartLogging"

    critical_actions:
      - "cloudtrail:DeleteTrail"
      - "cloudtrail:StopLogging"

  # AWS Secrets Manager - Credential management (CRITICAL)
  secretsmanager:
    read_only_actions:
      - "secretsmanager:DescribeSecret"
      - "secretsmanager:ListSecrets"
      - "secretsmanager:ListSecretVersionIds"

    medium_risk_actions:
      - "secretsmanager:GetSecretValue"    # Reading secrets is medium risk
      - "secretsmanager:CreateSecret"
      - "secretsmanager:UpdateSecret"
      - "secretsmanager:TagResource"
      - "secretsmanager:UntagResource"

    high_risk_actions:
      - "secretsmanager:PutSecretValue"
      - "secretsmanager:UpdateSecretVersionStage"
      - "secretsmanager:RestoreSecret"

    critical_actions:
      - "secretsmanager:DeleteSecret"
      - "secretsmanager:CancelDeletionSecret"

  # AWS Certificate Manager - SSL/TLS certificates (HIGH security impact)
  acm:
    read_only_actions:
      - "acm:DescribeCertificate"
      - "acm:ListCertificates"
      - "acm:GetCertificate"

    medium_risk_actions:
      - "acm:RequestCertificate"
      - "acm:ImportCertificate"
      - "acm:AddTagsToCertificate"
      - "acm:RemoveTagsFromCertificate"

    high_risk_actions:
      - "acm:ResendValidationEmail"
      - "acm:RenewCertificate"

    critical_actions:
      - "acm:DeleteCertificate"

  # AWS Systems Manager - System management (HIGH risk for lateral movement)
  ssm:
    read_only_actions:
      - "ssm:DescribeInstanceInformation"
      - "ssm:DescribeParameters"
      - "ssm:GetParameter"
      - "ssm:GetParameters"
      - "ssm:GetParameterHistory"
      - "ssm:DescribeDocumentParameters"
      - "ssm:ListDocuments"
      - "ssm:DescribeDocument"

    medium_risk_actions:
      - "ssm:PutParameter"
      - "ssm:DeleteParameter"
      - "ssm:DeleteParameters"
      - "ssm:AddTagsToResource"
      - "ssm:RemoveTagsFromResource"

    high_risk_actions:
      - "ssm:SendCommand"                  # Remote command execution
      - "ssm:StartSession"                 # Session Manager access
      - "ssm:CreateDocument"
      - "ssm:UpdateDocument"

    critical_actions:
      - "ssm:DeleteDocument"
      - "ssm:ModifyDocumentPermission"

  # AWS Organizations - Account management
  organizations:
    read_only_actions:
      - "organizations:DescribeOrganization"
      - "organizations:ListAccounts"
      - "organizations:ListRoots"
      - "organizations:ListOrganizationalUnits"
      - "organizations:ListPolicies"
      - "organizations:DescribeAccount"
      - "organizations:DescribePolicy"

    high_risk_actions:
      - "organizations:CreateAccount"
      - "organizations:CreateOrganizationalUnit"
      - "organizations:MoveAccount"
      - "organizations:AttachPolicy"
      - "organizations:DetachPolicy"
      - "organizations:CreatePolicy"
      - "organizations:UpdatePolicy"

    critical_actions:
      - "organizations:CloseAccount"
      - "organizations:DeleteOrganization"
      - "organizations:DeleteOrganizationalUnit"
      - "organizations:DeletePolicy"
      - "organizations:LeaveOrganization"

# Managed policy scoring
managed_policies:
  # Critical risk policies
  critical:
    - "AdministratorAccess"
    - "IAMFullAccess"
    - "OrganizationsFullAccess"
    - "PowerUserAccess"

  # High risk policies
  high:
    - "EC2FullAccess"
    - "S3FullAccess"
    - "RDSFullAccess"
    - "LambdaFullAccess"
    - "CloudFormationFullAccess"

  # Medium risk policies
  medium:
    - "EC2InstanceProfileForImageBuilder"
    - "AmazonS3ReadOnlyAccess"
    - "AmazonEC2ReadOnlyAccess"

  # Low risk policies (read-only)
  low:
    - "ReadOnlyAccess"
    - "ViewOnlyAccess"
    - "AWSSupportAccess"
    - "CloudWatchReadOnlyAccess"
    - "CloudTrailReadOnlyAccess"

# Pattern-based scoring for unknown actions
patterns:
  critical:
    - "*:*"                    # Wildcard permissions
    - "*"                      # Full wildcard

  high:
    - ".*:Delete.*"           # Delete operations
    - ".*:Create.*Role.*"     # Role creation
    - ".*:Create.*Policy.*"   # Policy creation
    - ".*:Attach.*Policy.*"   # Policy attachment
    - ".*:Put.*Policy.*"      # Policy modification

  medium:
    - ".*:Create.*"           # General creation
    - ".*:Update.*"           # Updates
    - ".*:Modify.*"           # Modifications
    - ".*:Put.*"              # Put operations

  low:
    - ".*:Get.*"              # Get operations
    - ".*:List.*"             # List operations
    - ".*:Describe.*"         # Describe operations
    - ".*:View.*"             # View operations

# Score calculation weights
weights:
  service_specific: 1.0       # Weight for service-specific scoring
  pattern_based: 0.7          # Weight for pattern-based scoring when no service match
  managed_policy: 1.2         # Weight for managed policy scoring
